[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "bc1c7864687d3b74f2c68694fd3a73d7357731f9"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "3945aa4613af776daf153d32a45cc43416bc83333e28450944813932538242a5"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "864a7a47d98ddb8952cbd6eda3f2d9e4dafba465"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "2ddbce3cfed4632e6d347fd9449f88b811b70b01c2a481672c7488dbdddb086c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "e06b792946e7a5966f1c0dc1b31d617cff6a5072"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "5dd96b59c0bbde31f7459976c5cf4bbb375c5c30a3a86c46cda72efed9e37e58"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "cd7a09e544f7846a8aecdb6fba58903e50b664c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "39e704bdd6922e81395f1523f99b3c1964465ce63d381da2b8a106ef8ca2eded"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "1948a9ddd55c3a5c361d154ed6c94c0e21a7a4eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "0c107c86b34a703d6cbab7e12b0e7d084c268eee60fddbcbfb39c31c9e26c755"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "21ef4c8e36340ad47a8e1f2627bc2a4a96aadd9a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "8e553e2803262f06497149e3c784e3688cebabd162a7116edce90a2b5dc89554"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "aarch64"
git-tree-sha1 = "1b24967014b7a40f0cb6aad56c1a6e3e2521a858"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "9d9e2c4f71c6d238b25de10ade91d2844478a79c2ea5b57a3c6f36d2c36cb505"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56485cc3098bb5b7b5a6c9fa05087681c23d5d0b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "938a402d68a987e4ca19606fc59accd0ecc4e13c55f08372ff2738cd959e0ebc"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b57f170e5dc10c182eb0eface161e1826e44907a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "c79d39b1cfe640b8e81b83247ec3327be84bba44ccaa65a87c3f7e500535a908"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e21ad85b6af7ab7637f9fad3d496084c63ebb8a0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "2b2d84aa55e9c9e08ffa4cc0af1b37d7ce710d7cd4a5d6c4a29189345a184d22"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "955f0def188d8366ff75d8bf4323d5277acccd38"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "fef92a68a0f29765d31aff2c50837ffa4c18e16ea1e80ce150f1b8408a083bfc"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03c26e52ecb545d2eef1763b66a1671f6e8d9137"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "fd64e2df6b868bd4cfb1ea77c567f6fb42ea91ec98088faad6713995912ede0e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "738877389cc32989c08a69d7a0939286d5b329a1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "3e06430bf333a53320c6a82a07b9339ae7c5bb59fa2a3092f63f15b9901e7eca"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5ace1b5592d0a48990448b61548d792667bbf892"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "8d2f1d8a3d1af49689616c242ce5a3ff70db298d4aba72c0e45c6915f7f74884"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e40d5025b2ad2669e8d7650948128c7a1f2e44a0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "26fcff27dea08de1d65413e7de534d1890ceb3ee8a79f070828988175236228a"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2fbc66321fc5dee9da4540d32e6b549d43418395"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "a6fd6df080e2952f7acbe7cb3034b669495abca6f91da7e192afb1ba183f748b"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50db599f266a4441e44e6769ae1578fb28fc3cda"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "50b7b58a67d32af1164e74092c78c80c506e9c6376bebdd632d7c52298e58e8a"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25b306691fe034bb15560ec898484adeb56446c3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "5f67724da635c643c3a4c71ad1f7ccc234cdfc9946134fa404735bab03c2e584"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3b594a070372afea6c0981f970aeac243b59155"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "f2e9cba54ca3b020e670a0ee4616eaa28534bd223c7858d27d4773aaa7014fd3"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "5e1d374f3284208ff2442710db867c610e148c0b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "bee40f3be0a42ad931e0de946bb5c25ec4751cc9ce45f532ea78014ddf337b2a"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "ba319a09e9350419ccf8882ea10a97068dc17dcf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "399aac52d83227082f529cce6be4683be1014ab16c09fa34bef8d85d9ff1d37f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "624311550e156c053748797863a583915b5021a5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "14e16e86513f1714fe20d2269c81239588cfa0b2a8661904ce6eb7fecd43ccbd"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "9b7a521ea559f625e09ada751b8a1d7473d16a1e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "c9bf56fc8fbadb92f053a1a95c4c4fef364a2f7995342313cbc5b97ddbbcd18e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "4da349715d50ee63894a0f2452b55ffbdccdafa7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "207e4c4c0cfbbb4c051fcd0a814329d541b0f9901d7251d07ba479fb4af69f19"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "i686"
git-tree-sha1 = "68f833b17876508b879be05351610f06f7c58a6c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "ab764d1cfeee1d5e2f832c8086d63cca9a6fbbc7fc658dfb399781d3ebc818fe"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "17b7875a2eb936888e39594180a8934d07dec347"
libgfortran_version = "3.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "3e72cbf7e5c208391233d736fccbf1043a21206af19fcfee5c7dc20534579c70"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "51740b2f1734765c17fc0a5bb25b94aac93be1f0"
libgfortran_version = "4.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "1754b9b36a7a0be44a7986f87f3e788cac2967fd6a4161c46f3981b0318b0ed5"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "776ee8181d2086e1b926f670cd11ddb1d6fec784"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCALAPACK32.download]]
    sha256 = "c6ca54fde6e62f61c974e7b2f086c72b162283297e9dce23cb8b82ba9e6cb5b3"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "057fde3139b40e388fa8d8b5fa5ab759a826de8b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "6b62bda6df1b789b3b7850d50a863acc9b6917a640841afbfce63cf3256b8bd2"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "18966c3ac2b8a61c6f89d749df4a98dd941fcc12"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "f6f3219b72cb9805627e4976fa81ef66f738576b6d3291a1470a87684545ee76"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "dd8effd92150cf0ff8098dd48b85d725f02e16b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "2b5a73629626a017b6cd0c3e0b25c9b756ff09a25d83e4458ac4616d78a50415"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "9c8b083f2a7cd180bcfb328d60923774fb8538e5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "43bdaca3d26f23e404bcdf1d7d2b1d3645b5ca355c9228ac529e729c17a11e34"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "5debf6559aaf4546edb723bb6b36a5c92c40fbfc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "e92cc0f1613d08494ddec8f7081a3cb4a643b45f5412e316694273a1ed128459"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "c9fcd716934716e8bfc6722fc6ec706e95fdea64"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK32.download]]
    sha256 = "051a84f24ead4d416cd92c6e051c7dd1ab4242fe10b2010aab53587e6a377335"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "741f00bfae097935e56bd5ddc9abe965a3cd77cb"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SCALAPACK32.download]]
    sha256 = "53b697f9ab0fc59f81810d58fde9fe11bc7859e034b481cbeda9c58b453f1662"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "3435988c24e93e4fa123846c15cf1d19dde31dfd"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SCALAPACK32.download]]
    sha256 = "a0a8e6414535a64333b255bfb991bd2c18e5cae5d03ba9fe8ad10a6d8bc576b2"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SCALAPACK32]]
arch = "x86_64"
git-tree-sha1 = "c8c6c1a737e2298e2eae74eace8104710bdaebfc"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SCALAPACK32.download]]
    sha256 = "3bec57517c99ce5a265a5edc8b3ba895d62ff288f6a5d23fcef82d9aa4ff39ce"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK32_jll.jl/releases/download/SCALAPACK32-v2.1.0+0/SCALAPACK32.v2.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
