# Autogenerated wrapper script for SCALAPACK32_jll for aarch64-apple-darwin-libgfortran5-mpi+mpich
export libscalapack32

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("SCALAPACK32")
JLLWrappers.@declare_library_product(libscalapack32, "@rpath/libscalapack32.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libscalapack32,
        "lib/libscalapack32.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
