# Autogenerated wrapper script for SCALAPACK32_jll for i686-linux-musl-libgfortran5-mpi+mpiabi
export libscalapack32

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using mpif_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("SCALAPACK32")
JLLWrappers.@declare_library_product(libscalapack32, "libscalapack32.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, mpif_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libscalapack32,
        "lib/libscalapack32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
